Import the necessary libraries and dependencies

Notice that we import from `ecapa_classifier` instead of `modules`

In [69]:
from python_lib.ecapa_classifier import *
import torch
import numpy as np
import os
from python_lib.saveasfile import *

# Model initialisation 

Use BlockSave to save all the weights into a `.bin` file

Be sure to `load_state_dict` from a `.pt`/`.pth` file before BlockSave

It's omitted here as I don't have the weights on hand, so I just use a random initialised weights.

Here, specify the metrics_type you wish to use beforehand: `cosine` , `cdist`, `euclidean`

In [71]:
# This out_neurons is after fc. Hence, due to ASP previously, we set out_neuron = 1

# metrics_type = cosine / cdist / euclidean

model = ECAPA_TDNN(input_size = 2, 
                   channels=[8,8,8,8,16], 
                   lin_neurons=6, 
                   device = "cuda", 
                   out_neurons=1, 
                   metrics_type="euclidean").to("cuda")

BlockSave(model.return_layers(), "fullecapa_classifier_euclidean", "verifyCppVsPy")

# Generate Input Feats for testing purposes

In [5]:
input_feats = torch.rand([1,2,64]).to("cuda")
input_feats_np = input_feats.cpu().detach().numpy()
input_feats_np = np.reshape(input_feats_np, (2,64))
print(input_feats_np)
dim = input_feats_np.shape
print(dim)

flatten_inputs = input_feats_np.flatten()
with open(os.path.join("ECAPAweights", f"ecapainput_2x64.bin"), "wb") as f:
            # Write the dimensions down
            f.write(np.array(dim, dtype=np.int32).tobytes())
            # Write the flatten bias down
            f.write(flatten_inputs.tobytes())

[[0.38879645 0.57369834 0.80075717 0.7499905  0.8760568  0.5953407
  0.96687865 0.19404864 0.7338831  0.10817343 0.62204343 0.84491163
  0.4768408  0.1360389  0.4818855  0.46680504 0.7344077  0.49828732
  0.28713876 0.3497867  0.34029698 0.42403388 0.43592697 0.6064776
  0.5035775  0.6328213  0.3118136  0.47725874 0.6348506  0.27109456
  0.8729037  0.25773013 0.77347034 0.8676893  0.4192561  0.76917815
  0.64022374 0.40523994 0.57056236 0.7610243  0.12108201 0.4488796
  0.25404388 0.12344974 0.5311209  0.4324385  0.34555    0.49526536
  0.2983272  0.01218635 0.2760092  0.9437817  0.98549604 0.8738632
  0.17591423 0.43235713 0.90420544 0.7022316  0.3737064  0.17069173
  0.11870342 0.01647627 0.63169575 0.6427758 ]
 [0.62699103 0.43908495 0.22667372 0.20402795 0.994665   0.957396
  0.41751254 0.14722061 0.50215703 0.0728212  0.91050375 0.508045
  0.01895618 0.63508266 0.9619141  0.92489713 0.76009756 0.20702022
  0.4819011  0.8684529  0.4029696  0.6681574  0.46617973 0.11759371
  0.29655

# Run the model using eval/train mode

You may specify lengths here if necessary

Here, lengths = `0.4`

where 0 < lengths <= 1

In [6]:
model.eval()
 
# x = model(input_feats, lengths = None)
x= model(input_feats, lengths = torch.ones((1)) * 0.4)
x

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0421, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0945, 0.0170, 0.0450, 0.0000],
         [0.1113, 0.1685, 0.2785, 0.2402, 0.0813, 0.0025, 0.1535, 0.4634,
          0.0518, 0.1385, 0.1501, 0.0000, 0.2479, 0.1054, 0.0000, 0.0000,
          0.0849, 0.1740, 0.1762, 0.0000, 0.0000, 0.2020, 0.1083, 0.2765,
          0.3110, 0.1255, 0.2933, 0.0545, 0.2584, 0.1528, 0.0000, 0.3835,
          0.2098, 0.0945, 0.3515, 0.1258, 0.0388, 0.2440, 0.1586, 0.0990,
          0.0188, 0.0130, 0.0426, 0.1

tensor([[[0.1822, 0.1822, 0.1822, 0.0891, 0.1822, 0.1822],
         [0.1434, 0.1434, 0.1434, 0.2829, 0.1434, 0.1434],
         [0.1287, 0.1287, 0.1287, 0.3564, 0.1287, 0.1287],
         [0.1831, 0.1831, 0.1831, 0.0846, 0.1831, 0.1831],
         [0.1444, 0.1444, 0.1444, 0.2780, 0.1444, 0.1444],
         [0.1304, 0.1304, 0.1304, 0.3481, 0.1304, 0.1304]]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)

# Verification Test C++ vs Py

## Generating Test Inputs

**NOTE:** Change the values of `no_of_inputs, no_of_channel_in, no_of_input_width` accordingly to desired matrix size

Randomizes a `no_of_inputs x no_of_channel_in x no_of_input_width` matrix and saves the values into:
1. A binary (to feed C++ as input)
2. A CSV (to verify input values)

In [72]:
import pandas as pd

no_of_inputs = 1
no_of_channel_in = 2
no_of_input_width = 64

verify_feats = torch.rand([no_of_inputs,no_of_channel_in,no_of_input_width]).to("cuda")
print(verify_feats)
verify_feats_np = verify_feats.cpu().detach().numpy()

## Reshaping
if no_of_inputs == 1:
    verify_feats_np = np.reshape(verify_feats_np, (no_of_channel_in,no_of_input_width))
else:
    verify_feats_np = np.reshape(verify_feats_np, (no_of_inputs,no_of_channel_in,no_of_input_width)) 
dim = verify_feats_np.shape
print(dim)

## Writing verify inputs into binary
flatten_verify = verify_feats_np.flatten()
with open(os.path.join("verifyCppVsPy", f"testInput_ecapaClassifier_euclidean_{no_of_inputs}x{no_of_channel_in}x{no_of_input_width}.bin"), "wb") as f:
            # Write the dimensions down
            f.write(np.array(dim, dtype=np.int32).tobytes())
            # Write the flatten bias down
            f.write(flatten_verify.tobytes())
            
## Extracting verification input values into CSV
array_2d = verify_feats_np.reshape(no_of_inputs, -1)
output_df = pd.DataFrame(array_2d)
output_df.to_csv(f"verifyCppVsPy/testInput_ecapaClassifier_euclidean_{no_of_inputs}x{no_of_channel_in}x{no_of_input_width}.csv",\
                 header=False, index=False)
print(verify_feats_np)

tensor([[[0.5335, 0.4351, 0.2080, 0.5612, 0.4902, 0.2470, 0.6717, 0.7298,
          0.9509, 0.9651, 0.4484, 0.1278, 0.5818, 0.8657, 0.3780, 0.5560,
          0.5953, 0.0828, 0.1957, 0.2029, 0.6248, 0.9798, 0.9942, 0.3961,
          0.0348, 0.9022, 0.2809, 0.1619, 0.5822, 0.8474, 0.3472, 0.8883,
          0.3357, 0.0220, 0.9465, 0.7327, 0.8808, 0.8852, 0.8109, 0.7528,
          0.6354, 0.6015, 0.1990, 0.4482, 0.0028, 0.6637, 0.0919, 0.9655,
          0.8918, 0.4747, 0.2113, 0.2697, 0.5019, 0.5604, 0.5046, 0.1379,
          0.5977, 0.8454, 0.5719, 0.4211, 0.0064, 0.8176, 0.8037, 0.6596],
         [0.3584, 0.9438, 0.5027, 0.3487, 0.1564, 0.6694, 0.4910, 0.3885,
          0.3681, 0.3460, 0.4632, 0.7946, 0.5763, 0.5811, 0.9389, 0.1048,
          0.3185, 0.0519, 0.7239, 0.3592, 0.0368, 0.6738, 0.4336, 0.9585,
          0.0365, 0.8271, 0.9625, 0.3251, 0.6545, 0.3785, 0.0812, 0.4249,
          0.0602, 0.4942, 0.6217, 0.6444, 0.0364, 0.4049, 0.5248, 0.5406,
          0.3438, 0.1900, 0.6707, 0.8

In [84]:
model.eval()
 
# x = model(input_feats, lengths = None)
# y = model(verify_feats, lengths = torch.ones((1)) * 0.4)
y = model(verify_feats)

tensor([[[0.2000, 0.0949, 0.0572, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.1129, 0.0000, 0.0053,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.1968, 0.0000, 0.0350, 0.1725, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0266, 0.0000, 0.3487, 0.0000, 0.0000, 0.0000,
          0.0546, 0.0108, 0.2588, 0.2178, 0.0000, 0.1623, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0240, 0.0000, 0.0052, 0.0000, 0.0000, 0.0000],
         [0.3906, 0.2661, 0.3574, 0.1465, 0.3819, 0.3388, 0.4486, 0.3220,
          0.0620, 0.0000, 0.1901, 0.3827, 0.3094, 0.4143, 0.0976, 0.1904,
          0.0000, 0.3050, 0.4277, 0.4545, 0.5535, 0.0426, 0.1411, 0.0123,
          0.3279, 0.3374, 0.2130, 0.5194, 0.3045, 0.2605, 0.1690, 0.0000,
          0.3388, 0.3753, 0.5653, 0.1538, 0.1863, 0.1157, 0.1506, 0.1327,
          0.0000, 0.1813, 0.1882, 0.3

In [85]:
print(y)
print(y.cpu().detach().numpy())

tensor([[[1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.]]], device='cuda:0', grad_fn=<SoftmaxBackward0>)
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [66]:
h = torch.rand([2,3,4]).to("cuda")
h = h * 10

In [67]:
print(h)
print(h.sqrt())
print(h.sum(-1)) # Sum 1 = vertical sum, Sum -1 = horizontal sum

tensor([[[8.4011, 1.1172, 4.1824, 7.0907],
         [8.1731, 3.3377, 6.7031, 1.9289],
         [1.1986, 7.2020, 4.3505, 7.0309]],

        [[3.4503, 3.7960, 3.7190, 3.6708],
         [8.5701, 1.4724, 4.0164, 8.0232],
         [6.7687, 5.2350, 1.8173, 0.4282]]], device='cuda:0')
tensor([[[2.8985, 1.0570, 2.0451, 2.6628],
         [2.8589, 1.8269, 2.5890, 1.3888],
         [1.0948, 2.6837, 2.0858, 2.6516]],

        [[1.8575, 1.9483, 1.9285, 1.9159],
         [2.9275, 1.2134, 2.0041, 2.8325],
         [2.6017, 2.2880, 1.3481, 0.6544]]], device='cuda:0')
tensor([[20.7913, 20.1428, 19.7820],
        [14.6360, 22.0821, 14.2492]], device='cuda:0')
